var res = {
    CloseNormal_png : "res/CloseNormal.png",
    CloseSelected_png : "res/CloseSelected.png",
    mapa_micky : "res/aventuraGrafica/mapa_micky.tmx",
    escenario_micky_png : "res/aventuraGrafica/micky_escenario_1.png",
    mapa_albon : "res/aventuraGrafica/mapa_albon.tmx",
    escenario_albon_png : "res/aventuraGrafica/mapa_albon_png.png",
    playerrunright_png : "res/aventuraGrafica/playerrunright.png",
    playerrunright_plist : "res/aventuraGrafica/playerrunright.plist",
    playeridleright_png : "res/aventuraGrafica/playeridleright.png",
    playeridleright_plist : "res/aventuraGrafica/playeridleright.plist",
    mapa_kuzco : "res/aventuraGrafica/mapa_kuzco.tmx",
    escenario_kuzco_png : "res/aventuraGrafica/mapa_kuzco_png.png",
    mapa_ricardo : "res/aventuraGrafica/mapa_ricardo.tmx",
    mapa_ricardo_png : "res/aventuraGrafica/mapa_ricardo_png.png",
    pastilla_png : "res/aventuraGrafica/pastilla.png",
    tacataca_png : "res/aventuraGrafica/tacataca.png",
    escopeta_png : "res/aventuraGrafica/escopeta.png",
    acondicionador_png : "res/aventuraGrafica/acondicionador.png",
    calzoncillo_png : "res/aventuraGrafica/calzoncillo.png",
    parchePirata_png : "res/aventuraGrafica/parchePirata.png",
    anillo_png : "res/aventuraGrafica/anillo.png",
    espatula_png : "res/aventuraGrafica/espatula.png",
    boton_jugar_png : "res/boton_jugar.png",
    boton_jugar_pulsado_png : "res/boton_jugar_pulsado.png",
    menu_titulo_png : "res/menu_titulo.png",
    sonido_inicio_wav: "res/sonido_inicio.wav",
    textos_micky : "res/dialogos/Micky.json",
    textos_micky_fase2 : "res/dialogos/Micky_fase2.json",
    fondo_png : "res/dialogos/bar_inicio.png",
    fondo_micky_fase2 : "res/dialogos/micky_escenario.jpg",
    dialogos_jugador: "res/dialogos/plantillaDialogos_jugador.png",
    dialogos_papito: "res/dialogos/plantillaDialogos_papito.png",
    alberto_png : "res/dialogos/Alberto.png",
    blank_png : "res/dialogos/Blank.png",
    micky_png : "res/dialogos/Micky.png",
    ricardo_png : "res/dialogos/Ricardo.png",
    loose_json : "res/dialogos/Loose.json",
    moneda_png : "res/recolectorMonedas/moneda.png",
    moneda_plist : "res/recolectorMonedas/moneda.plist",
    fondo_jungla : "res/recolectorMonedas/fondo.png",
    droga_png : "res/recolectorMonedas/pastilla.png",
    musica_fondo_minijuego_RL : "res/recolectorMonedas/MusicvaMinijuegoRicardoLametones.wav",
    multa_png : "res/recolectorMonedas/papeles.png",
    cesta_png : "res/recolectorMonedas/gorra.png",
    game_over_png: "res/game_over.png",
    win_png: "res/win.png",
    cafe_png: "res/restaurante/cafe.png",
    cafewall_png: "res/restaurante/cafewall.png",
    cafe_tmx: "res/restaurante/cafe.tmx",
    camarero_png: "res/restaurante/camarero.png",
    camarero_plist: "res/restaurante/camarero.plist",
    clientes_png: "res/restaurante/clientes.png",
    comida1_bt_png: "res/restaurante/albondigas_bt.png",
    comida1_bt_pres_png: "res/restaurante/albondigas_bt_pres.png",
    comida2_bt_png: "res/restaurante/helado_bt.png",
    comida2_bt_pres_png: "res/restaurante/helado_bt_pres.png",
    comida3_bt_png: "res/restaurante/burger_bt.png",
    comida3_bt_pres_png: "res/restaurante/burger_bt_pres.png",
    comida4_bt_png: "res/restaurante/patatas_bt.png",
    comida4_bt_pres_png: "res/restaurante/patatas_bt_pres.png",
    mesa_png: "res/restaurante/mesa_icon.png",
    reloj_png: "res/restaurante/reloj_icon.png",
    comida1_png: "res/restaurante/albondigas.png",
    comida2_png: "res/restaurante/helado.png",
    comida3_png: "res/restaurante/burger.png",
    comida4_png: "res/restaurante/patatas.png",
    sonido_restaurante_wav: "res/restaurante/sonido_restaurante.wav",
    sonido_atender_wav: "res/restaurante/sonido_atender.wav",
    sonido_pedido_bien_wav: "res/restaurante/sonido_pedido_bien.wav",
    sonido_pedido_mal_wav: "res/restaurante/sonido_pedido_mal.wav",
    sonido_recoger_wav: "res/restaurante/sonido_recoger.wav",
    sonido_win_wav: "res/sonido_win.wav",
    sonido_game_over_wav: "res/sonido_game_over.wav",
    sonido_nuevo_cliente_wav: "res/restaurante/sonido_nuevo_cliente.wav"


};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}